### ISSUE TITLE
Informative article for the Spanish-speaking community

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/marketing#10]
Hello! I have thought of writing an informative article for the Spanish-speaking community. I think it is a good moment now that the project is about to take a big step with the joining of an open government foundation.

**Comment by derberg** [comment]
yes yes yes
so far feedback to open governance is just positive. I see no obstacles so far. We are joining a foundation in 1-2 weeks so you should definitely explore the subject

**Comment by Barbanio** [comment]
Ok Lukasz, I will work on it. This is the article worksheet link: https://docs.google.com/document/d/1Z3VN2GDwoZsv1Ry18ihR5aYxbcv3AZZj/edit
