### ISSUE TITLE
Writing a new article

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/marketing#17]
Hi! I thought I would write a new article about the cultural diversity that makes up AsyncAPI and the positive impact this has.

**Comment by derberg** [comment]
makes sense, just take into account that you already have 2 articles that are ready to be published, and then should be released with some "time" distance, so just not sure if it is good to work on another article now.

**Comment by Barbanio** [comment]
How about starting this article? One of the previous ones has already been published and another one is under review.

**Comment by derberg** [comment]
What would it be about? what cultural diversity you have in mind? I'm a bit skeptical regarding this one, comparing to previous articles...I'm probably biased 😄

**Comment by Barbanio** [comment]
Thanks for your feedback Lukasz 🙂

AsyncAPI is a multicultural community, I think that like the previous topics, it is one of the main characteristics of the project. Without talking about any specific culture, nor nationality, nor gender, I think that the topic can be tackled from a generalist approach, building in a positive way. By dealing with the enriching factor that this concept brings.

It can also be interpreted as a too delicate subject, I understand this positioning as well. 

Any suggestions are welcome, of course!
