### ISSUE TITLE
Blog post proposal

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/marketing#18]
## Git, Github, VS Code and Markdown for non-programmers

The last few weeks I've been getting closer to the world of Git, GitHub, VS Code and Markdown. I come from the world of communication so all these tools were totally unknown to me. I would like to share my first impressions in this area. I think this post could be helpful to people who are living or are going to live this experience.

**Comment by derberg** [comment]
Sounds great to me. Where would it be published? AsyncAPI Blog?

**Comment by Barbanio** [comment]
Fran has suggested that for AsyncAPI Blog, I think it's a good idea. What do you think?

**Comment by derberg** [comment]
yup, I think it is a good fit, just make sure you relate to AsyncAPI when possible
