### ISSUE TITLE
Possible CodelyTV promotional video about AsyncAPI Studio Tool

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/marketing#19]
CodelyTV is a Spanish-speaking YouTube channel that broadcasts training for programmers and divulgation of the development world. In their program of 9th Nov 2021 they dedicated part of the video (from minute 35:34 to 45:31) to talk about AsyncAPI Studio Tool (https://www.youtube.com/watch?v=EVLFwbyLX3A&t=2230s).  @alequetzalli  came up with the great idea of asking them if we could use this video section as a marketing tool. @mcturco  proposed to put subtitles in English to reach the widest possible audience.

**Comment by alequetzalli** [comment]
@Barbanio they already responded to me on Twitter private message and they have also asked if we would also like to schedule and plan a whole new stream with them that is only for that studio tool. ￼Do you want me to connect them with you to plan that stream or what should we do for that?￼

**Comment by Barbanio** [comment]
@alequetzalli What great news! I think it's a very good idea. If you want you can give them my contact and we'll close the stream if that's okay with you.

**Comment by alequetzalli** [comment]
For sure! I will give them your email and have them organize it with you :D ￼

**Comment by Barbanio** [comment]
Thanks a lot :)

**Comment by alequetzalli** [comment]
Ok, @Barbanio, here is the Calendly link from CodelyTV, so that you can schedule some time to work with them on this! :) 

https://calendly.com/d/cfd-4jh-b27/videollamada?month=2021-11

**Comment by Barbanio** [comment]
Thank you very much @alequetzalli

**Comment by Barbanio** [comment]
I have been talking to Rafa from Codely.TV and they let us use the video clip where they talk about AsyncAPI. 
They also propose us two things:

1. Course:
- To take a course with them on how to use AsyncAPI.
- It would be a collaboration and someone from the team would have to go to Barcelona to record the course.
- The accommodations costs would be paid.

2. Live video through YouTube:
- To make a live 1 hour live show on how to use AsyncAPI.
- This would be done remotely.

I have many doubts about the course since they charge a monthly or yearly fee to their users to access their courses. I think we could do it on our own and make the access free and open access.

Regarding the live video, I think it is a very good idea as it would help us to reach more users and it is open access.

What do you think?
It would be in Spanish, that's why I mainly tag Spanish-speaking mates: @alequetzalli @fmvilas @smoya @derberg (definitely, we know that you know Spanish)

**Comment by fmvilas** [comment]
I'd go forward with a live video as long as it's open and free for everyone to watch it. I can do it myself, it's been a lot of time since we recorded the other one. Gotta be fun 😄

**Comment by Barbanio** [comment]
Great 🙂
