### ISSUE TITLE
Creating a list of media

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/marketing#4]
Hello! We are collecting information on media devoted to the technological world. The goal is to create a list of journals, magazines, webs, blogs, etc., that we could use later for publishing news about AsyncAPI. If you wanna contribute to it, just let us know... proposals are welcome :)
https://docs.google.com/spreadsheets/d/1gJcsaxHKuDp7Ky8ZmWcrn91RzZN7WFLf/edit#gid=952211079

**Comment by fmvilas** [comment]
Awesome list! :clap: I'd suggest converting it to a Google Sheet so we can sort and filter by different criteria. For instance, it would be great to sort by "importance" or "impact". What do you think?

**Comment by Barbanio** [comment]
Great idea. We will work on it :)
