### ISSUE TITLE
Communication analysis and proposals

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/marketing#9]
Hello! We are working on a document analysing the communication strategies that have been implemented so far, in which we include some proposals.

**Comment by fmvilas** [comment]
Are there any documents we can have a look into?

**Comment by Barbanio** [comment]
Yes, this is the link: https://docs.google.com/document/d/1WJag-mAnorqCYUr5m5Zc-cXyAEvF83ni/edit

**Comment by fmvilas** [comment]
Thank you!
